"""empty message

Revision ID: 2c0b0aa24af8
Revises: d901fad13f45
Create Date: 2019-05-23 22:52:24.152106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0b0aa24af8'
down_revision = 'd901fad13f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('person', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('person', sa.Column('phone', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'person', ['first_name'])
    op.create_unique_constraint(None, 'person', ['last_name'])
    op.create_unique_constraint(None, 'person', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'phone')
    op.drop_column('person', 'last_name')
    op.drop_column('person', 'first_name')
    # ### end Alembic commands ###
