"""empty message

Revision ID: 565b5066ffe5
Revises: 715e58928d3e
Create Date: 2019-05-24 16:16:08.288993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565b5066ffe5'
down_revision = '715e58928d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
