"""empty message

Revision ID: 715e58928d3e
Revises: 44cf3bd646d1
Create Date: 2019-05-24 16:09:27.299917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715e58928d3e'
down_revision = '44cf3bd646d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    # ### end Alembic commands ###
