"""empty message

Revision ID: eba201f437cc
Revises: 2c0b0aa24af8
Create Date: 2019-05-23 23:28:06.279211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba201f437cc'
down_revision = '2c0b0aa24af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('first_name', table_name='person')
    op.drop_index('last_name', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('last_name', 'person', ['last_name'], unique=True)
    op.create_index('first_name', 'person', ['first_name'], unique=True)
    # ### end Alembic commands ###
